name: Send finished notification to Slack
on:
  workflow_call:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Get workflow conclusion
        uses: technote-space/workflow-conclusion-action@v3

      - name: Send completed notification to Slack
        if: env.WORKFLOW_CONCLUSION == 'success'
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": ":white_check_mark: Workflow ${{ github.workflow }} #${{github.run_number}} completed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: Workflow <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} #${{github.run_number}}> completed"
                  }
                }
              ]
            }

      - name: Send failure notification to Slack
        if: env.WORKFLOW_CONCLUSION == 'failure'
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": ":x: Workflow ${{ github.workflow }} #${{github.run_number}} failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":x: Workflow <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} #${{github.run_number}}> failed"
                  }
                }
              ]
            }